#数据库ip
mysql.address = ${MYSQL_HOST:127.0.0.1}
#数据库账号
mysql.username = ${MYSQL_USER:root}
#数据库密码 whb18772916901
mysql.password = ${MYSQL_PASSWORD:whb18772916901}
#redis地址
redis.address = ${REDIS_HOST:127.0.0.1}
#redis密码 mac:123456
redis.password = ${REDIS_PASSWORD:123456}


#邮箱用户名
mail.username= 1289066006@qq.com
#邮箱密码
mail.password = tluepopuavbphejj